{
 "title": "Elcentral",
 "time": { "from": "2024-12-15T22:28:23.595Z", "to": "2024-12-16T07:10:08.801Z" },
 "panels": [
  {
   "title": "Total förbrukning kWh",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elcentral_active_energy_kwh{job=\"elcentral\", direction=\"import\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Effektuttag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "elcentral_instantaneous_active_power_kw{job=\"elcentral\",phase=~\"L[123]$\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Fasbelastning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "elcentral_current_a{job=\"elcentral\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Spänning",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elcentral_voltage_v{job=\"elcentral\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Spänning per fas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "elcentral_voltage_v{job=\"elcentral\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}